require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'mocha/minitest'
require './lib/stat_tracker'
require './lib/game_teams_manager'
require './lib/game_manager'
require './lib/team_manager'
require './lib/game'
require './lib/team'
require './lib/game_teams'
require './lib/league_statistics'
require './lib/findable'
